x-environment: &default-environment
  DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
  VALKEY_URL: redis://valkey:6379
  SECRET_KEY: ${SECRET_KEY}
  EMAIL_URL: ${EMAIL_URL:-consolemail://}
  GLITCHTIP_DOMAIN: ${GLITCHTIP_DOMAIN}
  DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
  ENABLE_ADMIN: ${ENABLE_ADMIN:-False}
  ENABLE_OPENAPI: ${ENABLE_OPENAPI:-False}
  ENABLE_USER_REGISTRATION: ${ENABLE_USER_REGISTRATION:-True}
  ENABLE_ORGANIZATION_CREATION: ${ENABLE_ORGANIZATION_CREATION:-False}
  SKIP_INIT: ${SKIP_INIT:-False}

services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql

  valkey:
    image: valkey/valkey:9
    restart: unless-stopped

  web:
    image: ghcr.io/dragonjuno/glitchtip-kr:latest
    depends_on:
      - postgres
      - valkey
    ports:
      - "${PORT:-8000}:8000"
    environment:
      <<: *default-environment
      SERVER_ROLE: all_in_one
    restart: unless-stopped
    volumes:
      - uploads:/code/uploads

volumes:
  pg-data:
  uploads:
